### ISSUE TITLE
Override complianz styling for map placeholder

### ISSUE THREAD

**Issue by moritzgvt** [fouadvollmer/theme#21]
Use this code to override the misstyling of the complianz map placeholder.

```css
footer .cmplz-placeholder-1 {
  background-color: unset;
}
```
