### ISSUE TITLE
Add firefox workaround for gallery module

### ISSUE THREAD

**Issue by moritzgvt** [fouadvollmer/theme#28]
Firefox renders the invisible margin of the gallery as scrollable content. Therefor in Firefox it needs to be set to 0:

```scss
// Place directly on the image tag of all gallery images

img {
  @-moz-document url-prefix() { 
    margin-bottom: 0;
  }
}
```
